pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out the code..'
                git 'https://github.com/TiagoPires25/devops-23-24-JPE-PSM-1231862'
            }
        }

        stage ('Assemble') {
            steps {
                echo 'Assembling the project..'
                dir('CA2/Part1/gradle_basic_demo') {
                    sh 'chmod +x gradlew'
                    sh './gradlew clean assemble'
                }
            }
        }

        stage ('Test') {
            steps {
                echo 'Testing the project..'
                dir('CA2/Part1/gradle_basic_demo') {
                    sh './gradlew test'
                }
            }
            post {
                always {
                    junit 'CA2/Part1/gradle_basic_demo/build/test-results/test/*.xml'
                }
            }
        }

        stage ('Archive') {
            steps {
                echo 'Archiving the project..'
                archiveArtifacts 'CA2/Part1/gradle_basic_demo/build/distributions/*'
            }
        }
    }
}