pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/TiagoPires25/devops-23-24-JPE-PSM-1231862-.git'
            }
        }

        stage('Assemble') {
            steps {
                dir('CA2/Part2/react-and-spring-data-rest-basic') {
                    script {
                        if (isUnix()) {
                            sh './gradlew assemble'
                        } else {
                            bat './gradlew assemble'
                        }
                    }
                }
            }
        }

        stage('Test') {
            steps {
                dir('CA2/Part2/react-and-spring-data-rest-basic') {
                    script {
                        if (isUnix()) {
                            sh './gradlew test'
                        } else {
                            bat './gradlew test'
                        }
                    }
                }
            }
            post {
                always {
                    junit '**/build/test-results/**/*.xml'
                }
            }
        }

        stage('Javadoc') {
            steps {
                dir('CA2/Part2/react-and-spring-data-rest-basic') {
                    script {
                        if (isUnix()) {
                            sh './gradlew javadoc'
                        } else {
                            bat './gradlew javadoc'
                        }
                    }
                }
            }
            post {
                always {
                    publishHTML(target: [
                            allowMissing         : false,
                            alwaysLinkToLastBuild: false,
                            keepAll              : true,
                            reportDir            : 'CA2/Part2/react-and-spring-data-rest-basic/build/docs/javadoc',
                            reportFiles          : 'index.html',
                            reportName           : 'Javadoc'
                    ])
                }
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: '**/build/libs/*.war', fingerprint: true
            }
        }

        stage('Publish Image') {
            steps {
                script {
                    dir('CA5/Part2') {
                        script {
                            if (isUnix()) {
                                sh 'cp ../../CA2/Part2/react-and-spring-data-rest-basic/build/libs/*.war .'
                            } else {
                                bat 'copy ..\\..\\CA2\\Part2\\react-and-spring-data-rest-basic\\build\\libs\\*.war .'
                            }
                        }
                        def app = docker.build("tiagopires1862/devops_23_24:${env.BUILD_NUMBER}")
                        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub_credentials') {
                            app.push()
                        }
                    }
                }
            }
        }
    }
}
