services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_Database
    container_name: CA4_Part2_db
    ports:
      - "8082:8082"
      - "9092:9092"
    volumes:
      - h2-data:/opt/h2-data
    networks:
      CA4_network:
        ipv4_address: 192.168.33.11

  web:
    build:
      context: .
      dockerfile: Dockerfile_Web
    container_name: CA4_Part2_web
    ports:
      - "8080:8080"
    networks:
      CA4_network:
        ipv4_address: 192.168.33.10
    depends_on:
      - "db"

volumes:
  h2-data:
    driver: local

networks:
  CA4_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.33.0/24
